import sys
import os
import grpc

# Add the server folder to the Python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'server')))

# Import the classes generated by gRPC
import service_pb2
import service_pb2_grpc

def run():
    # Create a channel to connect to the server at localhost on port 50051
    with grpc.insecure_channel('localhost:50051') as channel:
        stub = service_pb2_grpc.GreeterStub(channel)

        # Create the request object, passing "Mundo" (World) as the name
        request = service_pb2.HelloRequest(name="World")

        # Call the SayHello method from the server and get the response
        response = stub.SayHello(request)

        # Print the server response
        print(f"Server response: {response.message}")

if __name__ == '__main__':
    run()
